### ISSUE TITLE
Addon failing to copy amounts at random times

### ISSUE THREAD

**Issue by DainJJ** [tesu/PennyPincher#58]
Since the 7.2 drop, PennyPincher has been working erratically. More times than not it will not copy the amount after completing steps on the marketboard.

**Comment by tesu** [comment]
I'll look into it this weekend

**Comment by Xurtan** [comment]
Getting this too fwiw, thought it might have been my net or server lag but it's been consistent since 7.2. I tend to have to open the item history 4-5 times for a copy to go through.

**Comment by tesu** [comment]
From #known-issues in the XIVLauncher discord:

> # Compatibility Issues with ACT and FFXIV Teamcraft
> We've received reports that there may be compatibility issues between Dalamud and ACT/FFXIV Teamcraft. This compatibility issue will typically manifest as a crash to desktop on or after launching one of these apps. While the exact cause of this problem is still under investigation, it is currently believed to be a result of Patch 7.20's networking changes and multiple systems trying to access FFXIV's data simultaneously.
> 
> At present, the preliminary workaround is to disable plugins that capture and use networking data, or refrain from using external apps that interact with the game's networking data.

I have confirmed that disabling ACT (and Teamcraft) will cause Penny Pincher to work reliably again. I don't have an ETA on the broader fix.

**Comment by tesu** [comment]
Fixed by #59

**Comment by pokemonpasta** [comment]
Hi, I'm still having this issue. Been having it consistently since 7.2, have never had ACT or Teamcraft installed.

**Comment by MechMinotaur** [comment]
I recently encountered this issue after switching my operating system from Windows 10 to CachyOS. I checked the logs in `/xldev` but didn't see anything meaningful. As others have indicated, the problem seems to happen at random when trying to update prices on items for sale on markets by retainer. When this occurs, there's no history in the clipboard, almost like it was entirely skipped. I have the plugin IINACT installed, but not the application ACT nor the Teamcraft application.

I'd be glad to provide more information or conduct testing on my end if it'd be helpful, just let me know.

**Comment by DeScruff** [comment]
I'm having similar issues (Linux as well). - But I am unsure if the problem actually PennyPincher, or the game (Wine/proton/whatever it takes to run this game under Linux). As I have experienced issues with the clipboard when its come to this game. 
- Ive had it where pasting in game was a completely different thing then what I was pasting in say Discord.
